# Basics
site_name: MSDS 682 Data Stream Processing
site_url: https://pandaisfast.github.io/msds682-fall2023-data-streaming
site_author: Jeremy Wenxiao Gu
site_description: >-
  Data Streaming, Kafka, MSDS

# Repository
repo_name: pandaisfast/msds682-fall2023-data-streaming
repo_url: https://github.com/pandaisfast/msds682-fall2023-data-streaming

# Change the middle parameter to the default branch, "master" or "main"
edit_uri: edit/master/docs

# Copyright
copyright: Copyright &copy; 2023 Jeremy Wenxiao Gu

theme:
  logo: assets/usf_f_c_2c_rgb.png
  name: material
  language: 'en' 
  features:

    # if removed navigation.sections, the navation will collapse by default, unless using - navigation.expand 
    # - navigation.sections
    - navigation.tracking
    - navigation.indexes ## need some work here
    - navigation.top # Back to Top button
    - navigation.path #[paid feature]
    ## Tooltips #[paid feature]
    - content.tooltips
    # TOC
    # - toc.follow
    # - toc.integrate
    # When expansion is enabled, the left sidebar will expand all collapsible subsections by default
    # - navigation.expand 
  # colors
  palette:
    # Define the default light mode
    - scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Define the dark mode
    - scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # [paid feature] System preference setup for automatic theme switching
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search: # necessary for search to work
      lang:
        - en
        - de
        - ja
  - minify: # https://henrywhitaker3.github.io/mkdocs-material-dark-theme/plugins/minification/
      minify_html: true 
  # - git-revision-date-localized # Revision date https://henrywhitaker3.github.io/mkdocs-material-dark-theme/plugins/revision-date/
  # slide/images
  - glightbox
  # support for adding the date of last update and creation of a document at the bottom of each page
  # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=adding+a+git+repository#document-dates
  - git-revision-date-localized:
      enable_creation_date: true


# markdown_extensions:
  # TOC
  # - toc:
  #     permalink: true

markdown_extensions:

  # ## Tooltips [paid feature]
  # - abbr
  # - pymdownx.snippets
  ## emoji and icon
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  ## Footnote
  - footnotes
  ## Annotations
  - attr_list
  - md_in_html ## images
  - pymdownx.superfences
  ## Admonitions
  - admonition
  - pymdownx.details
  # - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format




# Navigation
nav:
  - "Overview":
    - index.md
  - "Lec 1: 10/20 F (Room 156)":
    - lec1/index.md
    - "1.1": lec1/1.1.md
    - "1.2": lec1/1.2.md
    - "1.3": lec1/1.3.md
    - "1.4": lec1/1.4.md

  - "Lec 2: 10/24 T (Room 157)":
    - lec2/index.md
    - "2.1": lec2/2.1.md
    - "2.2": lec2/2.2.md
    - "2.3": lec2/2.3.md
    - "2.4": lec2/2.4.md

  - "Lec 3: 10/27 F (Room 156)":
    - lec3/index.md
    - "3.1": lec3/3.1.md
    - "3.2": lec3/3.2.md
    - "3.3": lec3/3.3.md
    - "3.4": lec3/3.4.md

  - "Lec 4: 10/31 T (Room 156)":
    - lec4/index.md
    - "4.1": lec4/4.1.md
    - "4.2": lec4/4.2.md
    - "4.3": lec4/4.3.md
    - "4.4": lec4/4.4.md

  - "Lec 5: 11/03 F (Room 156)":
    - lec5/index.md
    - "5.1": lec5/5.1.md
    - "5.2": lec5/5.2.md
    - "5.3": lec5/5.3.md
    - "5.4": lec5/5.4.md

  - "Lec 6: 11/07 T (Room 156)":
    - lec6/index.md
    - "6.1": lec6/6.1.md
    - "6.2": lec6/6.2.md
    - "6.3": lec6/6.3.md
    - "6.4": lec6/6.4.md

  - "Lec 7: 11/10 F (Room 529)":
    - lec7/index.md
    - "7.1": lec7/7.1.md
    - "7.2": lec7/7.2.md
    - "7.3": lec7/7.3.md
    - "7.4": lec7/7.4.md

  - "Lec 8: 11/14 T (Room 156)":
    - lec8/index.md
    - "8.1": lec8/8.1.md
    - "8.2": lec8/8.2.md
    - "8.3": lec8/8.3.md
    - "8.4": lec8/8.4.md

  - "Lec 9: 11/17 F (Room 156)":
    - lec9/index.md
    - "9.1": lec9/9.1.md
    - "9.2": lec9/9.2.md
    - "9.3": lec9/9.3.md
    - "9.4": lec9/9.4.md

  - "Lec 10: 11/21 T (Room 156)":
    - lec10/index.md
    - "10.1": lec10/10.1.md
    - "10.2": lec10/10.2.md
    - "10.3": lec10/10.3.md
    - "10.4": lec10/10.4.md

  - "Lec 11: 11/24 F (Room 156)":
    - lec11/index.md
    - "11.1": lec11/11.1.md
    - "11.2": lec11/11.2.md
    - "11.3": lec11/11.3.md
    - "11.4": lec11/11.4.md

  - "Lec 12: 11/28 T (Room 156)":
    - lec12/index.md
    - "12.1": lec12/12.1.md
    - "12.2": lec12/12.2.md
    - "12.3": lec12/12.3.md
    - "12.4": lec12/12.4.md

  - "Lec 13: 12/01 F (Room 156)":
    - lec13/index.md
    - "13.1": lec13/13.1.md
    - "13.2": lec13/13.2.md
    - "13.3": lec13/13.3.md
    - "13.4": lec13/13.4.md

  - "Lec 14: 12/05 T (Room 157)":
    - lec14/index.md
    - "14.1": lec14/14.1.md
    - "14.2": lec14/14.2.md
    - "14.3": lec14/14.3.md
    - "14.4": lec14/14.4.md


  - "Course Project":
    - "Project Introduction": course_project/project_intro.md
    - "Project Guidelines": course_project/project_guidelines.md
    - "Project Examples": course_project/project_examples.md
  - "Appendix 1: Frequently Asked Questions":
    - appendix1/index.md
  - "Appendix 2: Recommended Courses, Books, Videos, Blogs":
    - appendix2/index.md