# Basics
site_name: MSDS 682 Data Stream Processing
site_url: https://pandaisfast.github.io/msds682-fall2023-data-streaming
site_author: Jeremy Wenxiao Gu
site_description: >-
  Data Streaming, Confluent, Kafka, MSDS, University of San Francisco, usfca

# Repository
repo_name: pandaisfast/msds682-fall2023-data-streaming
repo_url: https://github.com/pandaisfast/msds682-fall2023-data-streaming

# Change the middle parameter to the default branch, "master" or "main"
edit_uri: edit/master/docs

# Copyright
copyright: Copyright &copy; 2023 Jeremy Wenxiao Gu

theme:
  logo: assets/usf_f_c_2c_rgb.png
  name: material
  language: 'en' 
  features:

    # if removed navigation.sections, the navation will collapse by default, unless using - navigation.expand 
    # - navigation.sections
    - navigation.tracking
    - navigation.indexes ## need some work here
    - navigation.top # Back to Top button
    - navigation.path #[paid feature]
    ## Tooltips #[paid feature]
    - content.tooltips
    # TOC
    # - toc.follow
    # - toc.integrate
    # When expansion is enabled, the left sidebar will expand all collapsible subsections by default
    # - navigation.expand 
    # code blocks
    - content.code.copy
  # colors
  palette:
    # Define the default light mode
    - scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Define the dark mode
    - scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # [paid feature] System preference setup for automatic theme switching
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search: # necessary for search to work
      lang:
        - en
        - de
        - ja
  - minify: # https://henrywhitaker3.github.io/mkdocs-material-dark-theme/plugins/minification/
      minify_html: true 
  # - git-revision-date-localized # Revision date https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/, https://henrywhitaker3.github.io/mkdocs-material-dark-theme/plugins/revision-date/
  
  # slide/images
  - glightbox
  # support for adding the date of last update and creation of a document at the bottom of each page
  # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=adding+a+git+repository#document-dates
  - git-revision-date-localized:
      fallback_to_build_date: false
      enable_creation_date: true
      type: timeago
      timezone: America/Los_Angeles
  # show jupyter https://github.com/danielfrg/mkdocs-jupyter
  - mkdocs-jupyter:
        include: ["*.ipynb"] # Default: ["*.py", "*.ipynb"]
        ignore: ["some-irrelevant-files/*.ipynb"]

# markdown_extensions:
  # TOC
  # - toc:
  #     permalink: true

markdown_extensions:

  # ## Tooltips [paid feature]
  # - abbr
  # - pymdownx.snippets
  ## emoji and icon
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  ## Footnote
  - footnotes
  ## Annotations
  - attr_list
  - md_in_html ## images
  - pymdownx.superfences
  ## Admonitions
  - admonition
  - pymdownx.details
  # - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # code-blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences



# Navigation
nav:
  - "Overview":
    - index.md
  - "Lec 1: 10/20 F (Room 529)":
    - lec1/index.md
    - "Additional Topics": lec1/1.1.md
    - "Demo 1": lec1/demo_or_exercise.md
    - "Assignment 1": lec1/assignment.md
  
  - "Lec 2: 10/24 T (Room 529)":
    - lec2/index.md
    - "Additional Topics": lec2/2.1.md
    - "Notebook - Create Topics": assets/msds-lec2-topic-producer/demo_a_creating_topic.ipynb
    - "Notebook - Async Producer": assets/msds-lec2-topic-producer/demo_b_producer_async.ipynb
    - "Notebook - Compare Sync vs Async": assets/msds-lec2-topic-producer/demo_c_producer_compare.ipynb
    - "Notebook - Async Producer w/ Serialization": assets/msds-lec2-topic-producer/demo_b_producer_serialization.ipynb
    - "Demo 2A": lec2/demo_2a.md
    - "Demo 2B": lec2/demo_2b.md
    
  - "Lec 3: 10/27 F (Room 529)":
    - lec3/index.md
    - "Additional Topics": lec3/3.1.md
    - "Notebook - Consumer": assets/msds-lec3-consumer/demo_d_consumer_v2.ipynb
    - "Demo 3A": lec3/demo_or_exercise.md
    - "Demo 3B": lec3/demo_or_exercise_2.md

  - "Lec 7: 11/10 F (Room 529)":
    - lec7/assignment3.md
